File and Directory Access
filecmp
filecmp.clear_cache()
filecmp.cmp()
filecmp.cmpfiles()
filecmp.DEFAULT_IGNORES
filecmp.dircmp
filecmp.dircmp.common
filecmp.dircmp.common_dirs
filecmp.dircmp.common_files
filecmp.dircmp.common_funny
filecmp.dircmp.diff_files
filecmp.dircmp.funny_files
filecmp.dircmp.left
filecmp.dircmp.left_list
filecmp.dircmp.left_only
filecmp.dircmp.report()
filecmp.dircmp.report_full_closure()
filecmp.dircmp.report_partial_closure()
filecmp.dircmp.right
filecmp.dircmp.right_list
filecmp.dircmp.right_only
filecmp.dircmp.same_files
filecmp.dircmp.subdirs
fileinput
fileinput.close()
fileinput.FileInput
fileinput.filelineno()
fileinput.filename()
fileinput.fileno()
fileinput.hook_compressed()
fileinput.hook_encoded()
fileinput.input()
fileinput.isfirstline()
fileinput.isstdin()
fileinput.lineno()
fileinput.nextfile()
fnmatch
fnmatch.filter()
fnmatch.fnmatch()
fnmatch.fnmatchcase()
fnmatch.translate()
glob
glob.escape()
glob.glob()
glob.iglob()
linecache
linecache.checkcache()
linecache.clearcache()
linecache.getline()
linecache.lazycache()
os.path
os.path.abspath()
os.path.basename()
os.path.commonpath()
os.path.commonprefix()
os.path.dirname()
os.path.exists()
os.path.expanduser()
os.path.expandvars()
os.path.getatime()
os.path.getctime()
os.path.getmtime()
os.path.getsize()
os.path.isabs()
os.path.isdir()
os.path.isfile()
os.path.islink()
os.path.ismount()
os.path.join()
os.path.lexists()
os.path.normcase()
os.path.normpath()
os.path.realpath()
os.path.relpath()
os.path.samefile()
os.path.sameopenfile()
os.path.samestat()
os.path.split()
os.path.splitdrive()
os.path.splitext()
os.path.supports_unicode_filenames
pathlib
pathlib.Path
pathlib.Path.chmod()
pathlib.Path.cwd()
pathlib.Path.exists()
pathlib.Path.expanduser()
pathlib.Path.glob()
pathlib.Path.group()
pathlib.Path.home()
pathlib.Path.is_block_device()
pathlib.Path.is_char_device()
pathlib.Path.is_dir()
pathlib.Path.is_fifo()
pathlib.Path.is_file()
pathlib.Path.is_mount()
pathlib.Path.is_socket()
pathlib.Path.is_symlink()
pathlib.Path.iterdir()
pathlib.Path.lchmod()
pathlib.Path.link_to()
pathlib.Path.lstat()
pathlib.Path.mkdir()
pathlib.Path.open()
pathlib.Path.owner()
pathlib.Path.read_bytes()
pathlib.Path.read_text()
pathlib.Path.readlink()
pathlib.Path.rename()
pathlib.Path.replace()
pathlib.Path.resolve()
pathlib.Path.rglob()
pathlib.Path.rmdir()
pathlib.Path.samefile()
pathlib.Path.stat()
pathlib.Path.symlink_to()
pathlib.Path.touch()
pathlib.Path.unlink()
pathlib.Path.write_bytes()
pathlib.Path.write_text()
pathlib.PosixPath
pathlib.PurePath
pathlib.PurePath.anchor
pathlib.PurePath.as_posix()
pathlib.PurePath.as_uri()
pathlib.PurePath.drive
pathlib.PurePath.is_absolute()
pathlib.PurePath.is_relative_to()
pathlib.PurePath.is_reserved()
pathlib.PurePath.joinpath()
pathlib.PurePath.match()
pathlib.PurePath.name
pathlib.PurePath.parent
pathlib.PurePath.parents
pathlib.PurePath.parts
pathlib.PurePath.relative_to()
pathlib.PurePath.root
pathlib.PurePath.stem
pathlib.PurePath.suffix
pathlib.PurePath.suffixes
pathlib.PurePath.with_name()
pathlib.PurePath.with_stem()
pathlib.PurePath.with_suffix()
pathlib.PurePosixPath
pathlib.PureWindowsPath
pathlib.WindowsPath
shutil
shutil.chown()
shutil.copy()
shutil.copy2()
shutil.copyfile()
shutil.copyfileobj()
shutil.copymode()
shutil.copystat()
shutil.copytree()
shutil.disk_usage()
shutil.Error
shutil.get_archive_formats()
shutil.get_terminal_size()
shutil.get_unpack_formats()
shutil.ignore_patterns()
shutil.make_archive()
shutil.move()
shutil.register_archive_format()
shutil.register_unpack_format()
shutil.rmtree()
shutil.rmtree.avoids_symlink_attacks
shutil.SameFileError
shutil.unpack_archive()
shutil.unregister_archive_format()
shutil.unregister_unpack_format()
shutil.which()
stat
stat.FILE_ATTRIBUTE_ARCHIVE
stat.FILE_ATTRIBUTE_COMPRESSED
stat.FILE_ATTRIBUTE_DEVICE
stat.FILE_ATTRIBUTE_DIRECTORY
stat.FILE_ATTRIBUTE_ENCRYPTED
stat.FILE_ATTRIBUTE_HIDDEN
stat.FILE_ATTRIBUTE_INTEGRITY_STREAM
stat.FILE_ATTRIBUTE_NO_SCRUB_DATA
stat.FILE_ATTRIBUTE_NORMAL
stat.FILE_ATTRIBUTE_NOT_CONTENT_INDEXED
stat.FILE_ATTRIBUTE_OFFLINE
stat.FILE_ATTRIBUTE_READONLY
stat.FILE_ATTRIBUTE_REPARSE_POINT
stat.FILE_ATTRIBUTE_SPARSE_FILE
stat.FILE_ATTRIBUTE_SYSTEM
stat.FILE_ATTRIBUTE_TEMPORARY
stat.FILE_ATTRIBUTE_VIRTUAL
stat.filemode()
stat.IO_REPARSE_TAG_APPEXECLINK
stat.IO_REPARSE_TAG_MOUNT_POINT
stat.IO_REPARSE_TAG_SYMLINK
stat.S_ENFMT
stat.S_IEXEC
stat.S_IFBLK
stat.S_IFCHR
stat.S_IFDIR
stat.S_IFDOOR
stat.S_IFIFO
stat.S_IFLNK
stat.S_IFMT()
stat.S_IFPORT
stat.S_IFREG
stat.S_IFSOCK
stat.S_IFWHT
stat.S_IMODE()
stat.S_IREAD
stat.S_IRGRP
stat.S_IROTH
stat.S_IRUSR
stat.S_IRWXG
stat.S_IRWXO
stat.S_IRWXU
stat.S_ISBLK()
stat.S_ISCHR()
stat.S_ISDIR()
stat.S_ISDOOR()
stat.S_ISFIFO()
stat.S_ISGID
stat.S_ISLNK()
stat.S_ISPORT()
stat.S_ISREG()
stat.S_ISSOCK()
stat.S_ISUID
stat.S_ISVTX
stat.S_ISWHT()
stat.S_IWGRP
stat.S_IWOTH
stat.S_IWRITE
stat.S_IWUSR
stat.S_IXGRP
stat.S_IXOTH
stat.S_IXUSR
stat.SF_APPEND
stat.SF_ARCHIVED
stat.SF_IMMUTABLE
stat.SF_NOUNLINK
stat.SF_SNAPSHOT
stat.ST_ATIME
stat.ST_CTIME
stat.ST_DEV
stat.ST_GID
stat.ST_INO
stat.ST_MODE
stat.ST_MTIME
stat.ST_NLINK
stat.ST_SIZE
stat.ST_UID
stat.UF_APPEND
stat.UF_COMPRESSED
stat.UF_HIDDEN
stat.UF_IMMUTABLE
stat.UF_NODUMP
stat.UF_NOUNLINK
stat.UF_OPAQUE
tempfile
tempfile.gettempdir()
tempfile.gettempdirb()
tempfile.gettempprefix()
tempfile.gettempprefixb()
tempfile.mkdtemp()
tempfile.mkstemp()
tempfile.mktemp()
tempfile.NamedTemporaryFile()
tempfile.SpooledTemporaryFile()
tempfile.tempdir
tempfile.TemporaryDirectory()
tempfile.TemporaryFile()